class APIKeyEnum(object):
	ATTRIBUTES = "Attributes"
	CLASSES = "Classes"
	CONST = "Const"
	DESCRIPTION = "Description"
	ENUMS = "Enums"
	FUNCTIONS = "Functions"
	INHERITS_FROM = "Inherits from"
	MEMBERS = "Members"
	NAME = "Name"
	NAMESPACES = "Namespaces"
	PARAMETERS = "Parameters"
	RETURNS = "Returns"
	STATIC = "Static"
	TYPE = "Type"
	IS_CONSTRUCTOR = "Is constructor"

class CompletionKeyEnum(object):
	CONTENTS = "contents"
	TRIGGER = "trigger"